---
- include: Fedora.yml
  when: ansible_distribution == 'Fedora'
  tags: system-update

- include: CentOS.yml
  when: ansible_distribution == 'CentOS'
  tags: system-update

- include: RedHat.yml
  when: ansible_distribution == 'RedHat'
  tags: system-update

- include: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: system-update
